;;; bubblegum-dark-theme.el --- Theme

;; Copyright (C) 2016 , edliaw

;; Author: edliaw
;; Version: 0.1
;; Package-Requires: ((emacs "24"))
;; Created with ThemeCreator, https://github.com/mswift42/themecreator.


;; This program is free software: you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation, either version 3 of the License, or
;; (at your option) any later version.

;; This program is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
;; GNU General Public License for more details.

;; You should have received a copy of the GNU General Public License
;; along with this program. If not, see <http://www.gnu.org/licenses/>.

;; This file is not part of Emacs.

;;; Commentary:

;;; Code:

 (deftheme bubblegum-dark)
 (let ((class '((class color) (min-colors 89)))
       (fg         "#dedede")
       (bg         "#141414")
       (black-0    "#272727")
       (black-1    "#3a3a3a")
       (black-2    "#4c4c4c")
       (blue-0     "#a3d1fe")
       (blue-1     "#65bcfe")
       (blue-2     "#58a4de")
       (cyan-0     "#a3fee6")
       (cyan-1     "#65fedc")
       (cyan-2     "#58dec0")
       (green-0    "#b5fea3")
       (green-1    "#8cfe65")
       (green-2    "#7ade58")
       (grey-0     "#cccccc")
       (grey-1     "#bababa")
       (grey-2     "#a9a9a9")
       (magenta-0  "#cea3fe")
       (magenta-1  "#b765fe")
       (magenta-2  "#a058de")
       (orange-0   "#feb1a3")
       (orange-1   "#fe8465")
       (orange-2   "#de7358")
       (red-0      "#fea3e9")
       (red-1      "#fe65e1")
       (red-2      "#de58c5")
       (yellow-0   "#fefca3")
       (yellow-1   "#fefc65")
       (yellow-2   "#dedc58"))
   (custom-theme-set-faces
   'bubblegum-dark
        `(default ((,class (:background ,bg :foreground ,fg))))
        `(font-lock-builtin-face ((,class (:foreground ,magenta-0))))
        `(font-lock-comment-face ((,class (:foreground ,grey-1))))
        `(font-lock-negation-char-face ((,class (:foreground ,orange-0))))
        `(font-lock-reference-face ((,class (:foreground ,orange-0))))
        `(font-lock-constant-face ((,class (:foreground ,orange-0))))
        `(font-lock-doc-face ((,class (:foreground ,grey-1))))
        `(font-lock-function-name-face ((,class (:foreground ,green-0 ))))
        `(font-lock-keyword-face ((,class (:bold ,class :foreground ,yellow-0))))
        `(font-lock-string-face ((,class (:foreground ,red-0))))
        `(font-lock-type-face ((,class (:foreground ,blue-0 ))))
        `(font-lock-variable-name-face ((,class (:foreground ,cyan-0))))
        `(font-lock-warning-face ((,class (:foreground ,red-1 :background ,black-0))))
        `(region ((,class (:background ,fg :foreground ,bg))))
        `(highlight ((,class (:foreground ,grey-1 :background ,black-1))))
        `(hl-line ((,class (:background  ,black-0))))
        `(fringe ((,class (:background ,black-0 :foreground ,grey-2))))
        `(cursor ((,class (:background ,black-1))))
        `(show-paren-match-face ((,class (:background ,red-1))))
        `(isearch ((,class (:bold t :foreground ,red-1 :background ,black-1))))
        `(mode-line ((,class (:box (:line-width 1 :color nil) :bold t :foreground ,grey-2 :background ,black-0))))
        `(mode-line-inactive ((,class (:box (:line-width 1 :color nil :style pressed-button) :foreground ,cyan-0 :background ,bg :weight normal))))
        `(mode-line-buffer-id ((,class (:bold t :foreground ,green-0 :background nil))))
        `(mode-line-highlight ((,class (:foreground ,yellow-0 :box nil :weight bold))))
        `(mode-line-emphasis ((,class (:foreground ,fg))))
        `(vertical-border ((,class (:foreground ,grey-1))))
        `(minibuffer-prompt ((,class (:bold t :foreground ,yellow-0))))
        `(default-italic ((,class (:italic t))))
        `(link ((,class (:foreground ,orange-0 :underline t))))
        `(org-code ((,class (:foreground ,grey-0))))
        `(org-hide ((,class (:foreground ,grey-2))))
        `(org-level-1 ((,class (:bold t :foreground ,grey-0 :height 1.1))))
        `(org-level-2 ((,class (:bold nil :foreground ,grey-1))))
        `(org-level-3 ((,class (:bold t :foreground ,grey-2))))
        `(org-level-4 ((,class (:bold nil :foreground ,black-2))))
        `(org-date ((,class (:underline t :foreground ,cyan-0) )))
        `(org-footnote  ((,class (:underline t :foreground ,grey-2))))
        `(org-link ((,class (:underline t :foreground ,blue-0 ))))
        `(org-special-keyword ((,class (:foreground ,green-0))))
        `(org-block ((,class (:foreground ,grey-1))))
        `(org-quote ((,class (:inherit org-block :slant italic))))
        `(org-verse ((,class (:inherit org-block :slant italic))))
        `(org-todo ((,class (:box (:line-width 1 :color ,grey-1) :foreground ,yellow-0 :bold t))))
        `(org-done ((,class (:box (:line-width 1 :color ,black-1) :bold t :foreground ,black-2))))
        `(org-warning ((,class (:underline t :foreground ,red-1))))
        `(org-agenda-structure ((,class (:weight bold :foreground ,grey-1 :box (:color ,grey-2) :background ,black-1))))
        `(org-agenda-date ((,class (:foreground ,cyan-0 :height 1.1 ))))
        `(org-agenda-date-weekend ((,class (:weight normal :foreground ,grey-2))))
        `(org-agenda-date-today ((,class (:weight bold :foreground ,yellow-0 :height 1.4))))
        `(org-agenda-done ((,class (:foreground ,black-2))))
        `(org-scheduled ((,class (:foreground ,blue-0))))
        `(org-scheduled-today ((,class (:foreground ,green-0 :weight bold :height 1.2))))
        `(org-ellipsis ((,class (:foreground ,magenta-0))))
        `(org-verbatim ((,class (:foreground ,grey-2))))
        `(org-document-info-keyword ((,class (:foreground ,green-0))))
        `(font-latex-bold-face ((,class (:foreground ,blue-0))))
        `(font-latex-italic-face ((,class (:foreground ,cyan-0 :italic t))))
        `(font-latex-string-face ((,class (:foreground ,red-0))))
        `(font-latex-match-reference-keywords ((,class (:foreground ,orange-0))))
        `(font-latex-match-variable-keywords ((,class (:foreground ,cyan-0))))
        `(ido-only-match ((,class (:foreground ,red-1))))
        `(org-sexp-date ((,class (:foreground ,grey-2))))
        `(ido-first-match ((,class (:foreground ,yellow-0 :bold t))))
        `(gnus-header-content ((,class (:foreground ,yellow-0))))
        `(gnus-header-from ((,class (:foreground ,cyan-0))))
        `(gnus-header-name ((,class (:foreground ,blue-0))))
        `(gnus-header-subject ((,class (:foreground ,green-0 :bold t))))
        `(mu4e-view-url-number-face ((,class (:foreground ,blue-0))))
        `(mu4e-cited-1-face ((,class (:foreground ,grey-0))))
        `(mu4e-cited-7-face ((,class (:foreground ,grey-1))))
        `(mu4e-header-marks-face ((,class (:foreground ,blue-0))))
        `(ffap ((,class (:foreground ,grey-2))))
        `(js2-private-function-call ((,class (:foreground ,orange-0))))
        `(js2-jsdoc-html-tag-delimiter ((,class (:foreground ,red-0))))
        `(js2-jsdoc-html-tag-name ((,class (:foreground ,cyan-0))))
        `(js2-external-variable ((,class (:foreground ,blue-0  ))))
        `(js2-function-param ((,class (:foreground ,orange-0))))
        `(js2-jsdoc-value ((,class (:foreground ,red-0))))
        `(js2-private-member ((,class (:foreground ,grey-1))))
        `(js3-warning-face ((,class (:underline ,yellow-0))))
        `(js3-error-face ((,class (:underline ,red-1))))
        `(js3-external-variable-face ((,class (:foreground ,cyan-0))))
        `(js3-function-param-face ((,class (:foreground ,grey-0))))
        `(js3-jsdoc-tag-face ((,class (:foreground ,yellow-0))))
        `(js3-instance-member-face ((,class (:foreground ,orange-0))))
        `(warning ((,class (:foreground ,red-1))))
        `(ac-completion-face ((,class (:underline t :foreground ,yellow-0))))
        `(info-quoted-name ((,class (:foreground ,magenta-0))))
        `(info-string ((,class (:foreground ,red-0))))
        `(icompletep-determined ((,class :foreground ,magenta-0)))
        `(undo-tree-visualizer-current-face ((,class :foreground ,magenta-0)))
        `(undo-tree-visualizer-default-face ((,class :foreground ,grey-0)))
        `(undo-tree-visualizer-unmodified-face ((,class :foreground ,cyan-0)))
        `(undo-tree-visualizer-register-face ((,class :foreground ,blue-0)))
        `(slime-repl-inputed-output-face ((,class (:foreground ,blue-0))))
        `(trailing-whitespace ((,class :foreground nil :background ,red-1)))
        `(rainbow-delimiters-depth-1-face ((,class :foreground ,fg)))
        `(rainbow-delimiters-depth-2-face ((,class :foreground ,blue-0)))
        `(rainbow-delimiters-depth-3-face ((,class :foreground ,cyan-0)))
        `(rainbow-delimiters-depth-4-face ((,class :foreground ,orange-0)))
        `(rainbow-delimiters-depth-5-face ((,class :foreground ,yellow-0)))
        `(rainbow-delimiters-depth-6-face ((,class :foreground ,fg)))
        `(rainbow-delimiters-depth-7-face ((,class :foreground ,blue-0)))
        `(rainbow-delimiters-depth-8-face ((,class :foreground ,cyan-0)))
        `(magit-item-highlight ((,class :background ,black-1)))
        `(magit-section-heading        ((,class (:foreground ,yellow-0 :weight bold))))
        `(magit-hunk-heading           ((,class (:background ,black-1))))
        `(magit-section-highlight      ((,class (:background ,black-0))))
        `(magit-hunk-heading-highlight ((,class (:background ,black-1))))
        `(magit-diff-context-highlight ((,class (:background ,black-1 :foreground ,grey-1))))
        `(magit-diffstat-added   ((,class (:foreground ,blue-0))))
        `(magit-diffstat-removed ((,class (:foreground ,cyan-0))))
        `(magit-process-ok ((,class (:foreground ,green-0 :weight bold))))
        `(magit-process-ng ((,class (:foreground ,red-1 :weight bold))))
        `(magit-branch ((,class (:foreground ,orange-0 :weight bold))))
        `(magit-log-author ((,class (:foreground ,grey-1))))
        `(magit-hash ((,class (:foreground ,grey-0))))
        `(magit-diff-file-header ((,class (:foreground ,grey-0 :background ,black-1))))
        `(lazy-highlight ((,class (:foreground ,grey-0 :background ,black-1))))
        `(term ((,class (:foreground ,fg :background ,bg))))
        `(term-color-black ((,class (:foreground ,black-1 :background ,black-1))))
        `(term-color-blue ((,class (:foreground ,green-0 :background ,green-0))))
        `(term-color-red ((,class (:foreground ,yellow-0 :background ,black-1))))
        `(term-color-green ((,class (:foreground ,blue-0 :background ,black-1))))
        `(term-color-yellow ((,class (:foreground ,cyan-0 :background ,cyan-0))))
        `(term-color-magenta ((,class (:foreground ,magenta-0 :background ,magenta-0))))
        `(term-color-cyan ((,class (:foreground ,red-0 :background ,red-0))))
        `(term-color-white ((,class (:foreground ,grey-0 :background ,grey-0))))
        `(rainbow-delimiters-unmatched-face ((,class :foreground ,red-1)))
        `(helm-header ((,class (:foreground ,grey-0 :background ,bg :underline nil :box nil))))
        `(helm-source-header ((,class (:foreground ,yellow-0 :background ,bg :underline nil :weight bold))))
        `(helm-selection ((,class (:background ,black-0 :underline nil))))
        `(helm-selection-line ((,class (:background ,black-0))))
        `(helm-visible-mark ((,class (:foreground ,bg :background ,black-1))))
        `(helm-candidate-number ((,class (:foreground ,bg :background ,fg))))
        `(helm-separator ((,class (:foreground ,blue-0 :background ,bg))))
        `(helm-time-zone-current ((,class (:foreground ,magenta-0 :background ,bg))))
        `(helm-time-zone-home ((,class (:foreground ,blue-0 :background ,bg))))
        `(helm-buffer-not-saved ((,class (:foreground ,blue-0 :background ,bg))))
        `(helm-buffer-process ((,class (:foreground ,magenta-0 :background ,bg))))
        `(helm-buffer-saved-out ((,class (:foreground ,fg :background ,bg))))
        `(helm-buffer-size ((,class (:foreground ,fg :background ,bg))))
        `(helm-ff-directory ((,class (:foreground ,green-0 :background ,bg :weight bold))))
        `(helm-ff-file ((,class (:foreground ,fg :background ,bg :weight normal))))
        `(helm-ff-executable ((,class (:foreground ,cyan-0 :background ,bg :weight normal))))
        `(helm-ff-invalid-symlink ((,class (:foreground ,magenta-1 :background ,bg :weight bold))))
        `(helm-ff-symlink ((,class (:foreground ,yellow-0 :background ,bg :weight bold))))
        `(helm-ff-prefix ((,class (:foreground ,bg :background ,yellow-0 :weight normal))))
        `(helm-grep-cmd-line ((,class (:foreground ,fg :background ,bg))))
        `(helm-grep-file ((,class (:foreground ,fg :background ,bg))))
        `(helm-grep-finish ((,class (:foreground ,grey-0 :background ,bg))))
        `(helm-grep-lineno ((,class (:foreground ,fg :background ,bg))))
        `(helm-grep-match ((,class (:foreground nil :background nil :inherit helm-match))))
        `(helm-grep-running ((,class (:foreground ,green-0 :background ,bg))))
        `(helm-moccur-buffer ((,class (:foreground ,green-0 :background ,bg))))
        `(helm-source-go-package-godoc-description ((,class (:foreground ,red-0))))
        `(helm-bookmark-w3m ((,class (:foreground ,blue-0))))
        `(company-echo-common ((,class (:foreground ,bg :background ,fg))))
        `(company-preview ((,class (:background ,bg :foreground ,cyan-0))))
        `(company-preview-common ((,class (:foreground ,black-0 :foreground ,grey-1))))
        `(company-preview-search ((,class (:foreground ,blue-0 :background ,bg))))
        `(company-scrollbar-bg ((,class (:background ,black-1))))
        `(company-scrollbar-fg ((,class (:foreground ,yellow-0))))
        `(company-tooltip ((,class (:foreground ,grey-0 :background ,bg :bold t))))
        `(company-tooltop-annotation ((,class (:foreground ,orange-0))))
        `(company-tooltip-common ((,class ( :foreground ,grey-1))))
        `(company-tooltip-common-selection ((,class (:foreground ,red-0))))
        `(company-tooltip-mouse ((,class (:inherit highlight))))
        `(company-tooltip-selection ((,class (:background ,black-1 :foreground ,grey-1))))
        `(company-template-field ((,class (:inherit region))))
        `(web-mode-builtin-face ((,class (:inherit ,font-lock-builtin-face))))
        `(web-mode-comment-face ((,class (:inherit ,font-lock-comment-face))))
        `(web-mode-constant-face ((,class (:inherit ,font-lock-constant-face))))
        `(web-mode-keyword-face ((,class (:foreground ,yellow-0))))
        `(web-mode-doctype-face ((,class (:inherit ,font-lock-comment-face))))
        `(web-mode-function-name-face ((,class (:inherit ,font-lock-function-name-face))))
        `(web-mode-string-face ((,class (:foreground ,red-0))))
        `(web-mode-type-face ((,class (:inherit ,font-lock-type-face))))
        `(web-mode-html-attr-name-face ((,class (:foreground ,green-0))))
        `(web-mode-html-attr-value-face ((,class (:foreground ,yellow-0))))
        `(web-mode-warning-face ((,class (:inherit ,font-lock-warning-face))))
        `(web-mode-html-tag-face ((,class (:foreground ,magenta-0))))
        `(jde-java-font-lock-package-face ((t (:foreground ,cyan-0))))
        `(jde-java-font-lock-public-face ((t (:foreground ,yellow-0))))
        `(jde-java-font-lock-private-face ((t (:foreground ,yellow-0))))
        `(jde-java-font-lock-constant-face ((t (:foreground ,orange-0))))
        `(jde-java-font-lock-modifier-face ((t (:foreground ,grey-0))))
        `(jde-jave-font-lock-protected-face ((t (:foreground ,yellow-0))))
        `(jde-java-font-lock-number-face ((t (:foreground ,cyan-0))))))

;;;###autoload
(when load-file-name
  (add-to-list 'custom-theme-load-path
               (file-name-as-directory (file-name-directory load-file-name))))

(provide-theme 'bubblegum-dark)

;; Local Variables:
;; no-byte-compile: t
;; End:

;;; bubblegum-dark-theme.el ends here
